"""Add watched_movie table

Revision ID: 202414bbffa1
Revises: 1c174dccc563
Create Date: 2025-04-06 02:33:19.391340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202414bbffa1'
down_revision = '1c174dccc563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('watched_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_movie')
    # ### end Alembic commands ###
